repo_name: "https://github.com/oneapi-src/oneDNN.git"
onednn_version: "v2.5.4"
bench_image: "cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec:dnnbench"


# 测试相关
thread_num: [1, 2, 4, 8]
ISA_set: ["AVX512_CORE_BF16"]
data_type: ["u8s8s8,f32"]
numa: "56-71"
