# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch_name'
        default: 'main'
      commit_id:
        description: 'commit id'
      dp_base_image:
        description: 'the image you want to build based on'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf'
      code_repo:
        description: 'the repo you wanna to build'
        default: 'https://github.com/alibaba/DeepRec.git'
      image_tag:
        description: 'the image tag of the image built just now:'
      deeprec_tag:
        description: 'build deeprec image'
        type: boolean
        default: 'true'
      deeprec_modelzoo_tag:
        description: 'build deeprec-modelzoo image'
        type: boolean
        default: 'true'
      latest:
        description: 'Tag as the latest'
        type: boolean
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: acc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: List input parameters
        run: |
          echo ' branch_name: ${{github.event.inputs.branch_name}}'
          echo ' commit_id: ${{github.event.inputs.commit_id}}'
          echo 'deeprec-modelzoo base image: ${{github.event.inputs.base_image}}'
          echo 'code repo: ${{github.event.inputs.code_repo}}'
          echo 'image_tag: ${{github.event.inputs.image_tag}}'
          echo 'Whether build deeprec image: ${{github.event.inputs.deeprec_tag}}'
          echo 'Whether build deeprec-modelzoo image: ${{github.event.inputs.deeprec_modelzoo_tag}}'
          echo 'Whether tag the image as the latest: ${{github.event.inputs.latest}}'
      - name: modify the config file by inputs params
        run: |
          currentTime=`date "+%Y-%m-%d-%H-%M-%S"`
          echo ${{github.event.inputs.latest}}
          cd /home/shanlin/
          if [[ -d image_build_temp_dir ]];then
            sudo rm -rf image_build_temp_dir
          fi 
          mkdir image_build_temp_dir && cd image_build_temp_dir
          git clone https://github.com/GosTraight2020/DeepRec_CI.git
          config_file='/home/shanlin/image_build_temp_dir/DeepRec_CI/acc_auc_benchmark/config.properties'
          bash_file='/home/shanlin/image_build_temp_dir/DeepRec_CI/acc_auc_benchmark/build/image_build-action.sh'
          sed -i '3c commit_id ${{github.event.inputs.commit_id}}' $config_file
          sed -i '4c branch_name ${{github.event.inputs.branch_name}}' $config_file
          sed -i '9c base_image_modelzoo ${{github.event.inputs.base_image}}' $config_file
          sed -i '19c code_repo ${{github.event.inputs.code_repo}}' $config_file
          sed -i '11c image_TAG ${{github.event.inputs.image_tag}}' $config_file

          if [[ ${{github.event.inputs.deeprec_tag}} == true ]];then
            sed -i '198c\   build_image deeprec12138 $base_image_deepRec_repo /whl_build/whl_package/whl_install.sh' $bash_file
          else
            sed -i '199c\   #build_image deeprec12138 $base_image_deepRec_repo /whl_build/whl_package/whl_install.sh' $bash_file
          fi
          
          if [[ ${{github.event.inputs.deeprec_modelzoo_tag}} == true ]];then
            sed -i '198c\   build_image deeprec-modelzoo12138 $base_image_modelzoo_repo /whl_build/whl_package/whl_install.sh' $bash_file
          else
            sed -i '199c\   #build_image deeprec-modelzoo12138 $base_image_modelzoo_repo /whl_build/whl_package/whl_install.sh' $bash_file
          fi
          
          echo --------------------------------------config.properties-------------------------------------------------
          cat $config_file
          echo ---------------------------------------------------------------------------------------------------------
          echo -------------------------------------image_build.sh-----------------------------------------------------
          cat $bash_file | tail -n 94 | head -n 23
          echo --------------------------------------------------------------------------------------------------------

      - name: run the build process
        run: |
          cd /home/shanlin/image_build_temp_dir/DeepRec_CI/acc_auc_benchmark/build
          if [[ ${{github.event.inputs.latest}} == true ]];then
              bash image_build-action.sh -l | tee /home/shanlin/githubCI.log
          else 
              bash image_build-action.sh | tee /home/shanlin/githubCI.log
          fi
          
      - name: output the result
        run: |          
          echo "the build process has been executed successfully"
          bash /home/shanlin/image_build_temp_dir/DeepRec_CI/acc_auc_benchmark/build/echoWhl.sh
      - name: Clean 
        run: |          
          sudo rm -rf /home/shanlin/image_build_temp_dir



