# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch_name'
        default: 'main'
      commit_id:
        description: 'commit id'
      base_image:
        description: 'the image you want to build based on'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf'
      code_repo:
        description: 'the repo you wanna to build'
        default: 'https://github.com/alibaba/DeepRec.git'
      latest:
        description: 'Tag as the latest'
        type: boolean
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: acc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: modify the config file by inputs params
        run: |
          currentTime=`date "+%Y-%m-%d-%H-%M-%S"`
          echo ${{github.event.inputs.latest}}

