# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch_name'
        default: 'main'
      commit_id:
        description: 'commit id'
      base_image:
        description: 'the image you want to build based on'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf'
      code_repo:
        description: 'the repo you wanna to build'
        default: 'https://github.com/alibaba/DeepRec.git'
      image_tag:
        description: 'the image tag of the image built just now:'
      latest:
        description: 'Tag as the latest'
        type: boolean
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: acc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: modify the config file by inputs params
        run: |
          currentTime=`date "+%Y-%m-%d-%H-%M-%S"`
          echo ${{github.event.inputs.latest}}
          cd /home/shanlin/
          if [[ -d image_build_temp_dir ]];then
            rm -rf image_build_temp_dir
          fi 
          mkdir image_build_temp_dir && cd image_build_temp_dir
          git clone https://github.com/GosTraight2020/DeepRec_CI.git
          config_file='/home/shanlin/image_build_temp_dir/DeepRec_CI/acc_auc_benchmark/config.properties'
          
          sed -i '3c commit_id ${{github.event.inputs.commit_id}}' $config_file
          sed -i '4c branch_name ${{github.event.inputs.branch_name}}' $config_file
          sed -i '9c base_image_modelzoo ${{github.event.inputs.base_image}}' $config_file
          sed -i '19c code_repo ${{github.event.inputs.code_repo}}' $config_file
          sed -i '11c image_TAG ${{github.event.inputs.image_tag}}' $config_file
          echo ----------------------------------------------------------------------------------------------
          cat $config_file
          echo ------------------------------------------------------------------------------------------------
          cd DeepRec_CI/acc_auc_benchmark/build
          if [[ ${{github.event.inputs.latest}} == true ]];then
              bash image_build-action.sh -l | tee /home/shanlin/githubCI.log
          else 
              bash image_build-action.sh | tee /home/shanlin/githubCI.log
          fi
          
          cd ~ && rm -rf /home/shanlin/image_build_temp_dir/
          
          echo "the build process has been executed successfully"
          echo "the image name is :cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:${{github.event.inputs.image_tag}}"
          echo "the image name is :cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec:${{github.event.inputs.image_tag}}"
