# This is a basic workflow to help you get started with Actions

name: distributed_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DeepRec_test_image:
        description: 'the image used to benchmark DeepRec'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:latest'
      TF_test_image:
        description: 'the image used to benchmark Stock TF'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf'
      model_list:
        description: 'Model list(use whitespace to saperate)'
        default: 'WDL DSSM DeepFM DLRM DIEN DIN'
      log_tag:
        description: 'Log Tag (used to tag you log file)'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  distribute_test:
    # The type of runner that the job will run on
    runs-on: distributed_test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: modify the config file by inputs params
        run: |
          currentTime=`date "+%Y-%m-%d-%H-%M-%S"`
          image_tag=$(echo ${{github.event.inputs.DeepRec_test_image}} | awk -F ":" '{print $2}')
          if [[ -z ${{github.event.inputs.log_tag}}} ]];then
              tag='$currentTime-$image_tag'
          fi
          tag='$currentTime-${{github.event.inputs.log_tag}}'        
          cd /home/shanlin/
          if [[ ! -d DeepRec_CI ]];then
              git clone https://github.com/GosTraight2020/DeepRec_CI.git
          fi      
          cd DeepRec_CI/ \
          &&git pull
          template_path=./distributed_benchmark/templates/
          template_path=$(cd $template_path && pwd)
          tf_template=$template_path/tf_template.yaml
          deeprec_template=$template_path/deeprec_template.yaml
          # modify the template
          sed -i '44c\              image: ${{github.event.inputs.DeepRec_test_image}}'  $deeprec_template \
          &&sed -i '91c\              image: ${{github.event.inputs.DeepRec_test_image}}'  $deeprec_template \
          &&sed -i '40c\              image: ${{github.event.inputs.TF_test_image}}'  $tf_template\
          &&sed -i '83c\              image: ${{github.event.inputs.TF_test_image}}'  $tf_template\
          echo "---------------------------------------------DeepRec_template.yaml--------------------------------------------"
          cat $deeprec_tempalte
          echo "----------------------------------------------------end-------------------------------------------------------"
          echo "------------------------------------------------tf_template.yaml----------------------------------------------"
          cat $tf_template
          echo "----------------------------------------------------end-------------------------------------------------------"       
          # produce the new template
          model_array=(${{github.event.inputs.model_list}})
          declare -i model_num=${#model_array[@]}
          echo "the number of model is $model_num"        
          declare -i iter=0
          model_list=()
          for model in ${{github.event.inputs.model_list}}
          do
            if [[ $iter == $model_num-1 ]];then
                model_list[iter]=\"$model\"
            fi
            model_list[iter]="\"$model\", "
            iter=$iter+1
            echo $iter
            echo ${model_list[@]}
          done
          echo ${model_list[@]}
          sed -i "28c\    model_list = [ ${model_list[@],,} ]" ./distributed_benchmark/gen_template.py \
          &&sed -i "29c\    model_name_list = [ ${model_list[@]} ]" ./distributed_benchmark/gen_template.py\
          &&echo "------------------------------------------------gen_template.py----------------------------------------------"\
          &&cat ./distributed_benchmark/gen_template.py\
          &&echo "----------------------------------------------------end-------------------------------------------------------"\
          &&sudo rm -f ./distributed_benchmark/yaml_file/* \
          &&python3 ./distributed_benchmark/gen_template.py         
      - name: run the distributed test
        run: |          
          cd ./distributed_benchmark/ \
          && bash -x distributed_test.sh
          
          if [[ $? == 1 ]];then
            echo "The UT has not been finished"
            exit 1
          fi
      - name: output infomation
        run: |
          echo "the distributed benchmark has been finished"
          echo "the output log file will be put in the directory /home/shanlin/DeepRec_CI/distributed_benchmark/logs/$currentTime/"
