# This is a basic workflow to help you get started with Actions

name: gstep_benmark

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deeprec_test_image:
        description: 'DeepRec Benchmark Image'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:latest'
      tf_test_image:
        description: 'STOCK TF Benchmark Image'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf'
      model_list:
        description: 'Model list'
        default: 'WDL DSSM DeepFM DLRM DIEN DIN'
      deeprec_params:
        description: 'DeepRec Benchmark Parameters'
        default: |
          "--timeline 1000 
          --fusion"
      tf_params:
        description: 'TF Benchmark Parameters'
        default: |
          '--timeline 1000'
      cpu:
        description: 'CPU'
        default: '24-47'
      env_var:
        description: 'Environment Variables'
        default: |
          "export START_STATISTIC_STEP=100
          export STOP_STATISTIC_STEP=200
          export MALLOC_CONF=\"background_thread:true,metadata_thp:auto,dirty_decay_ms:60000,muzzy_decay_ms:60000\"
          export TF_LAYOUT_PASS_GRAPH_CAST_FUSION=1"
      weekly_tag:
        description: 'Regression Benmark'
        type: boolean
        default: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gstep_benchmark:
    # The type of runner that the job will run on
    runs-on: gstep_benchmark

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: modify the config file by inputs params
        run: |
           config_file="/home/shanlin/DeepRec_CI/gstep_benchmark/config.properties"
           cd /home/shanlin/
           if [[ ! -d DeepRec_CI ]];then
               git clone https://github.com/GosTraight2020/DeepRec_CI.git
           fi
           cd ./DeepRec_CI/
           && git pull \
           && cd ./gstep_benchmark/ \
           && sed -i "2c, deeprec_test_image ${{github.event.inputs.deeprec_test_image}}" $config_file\
           && sed -i "3c, tf_test_image ${{github.event.inputs.tf_test_image}}" $config_file\
           && sed -i "17c, cpus ${{github.event.inputs.cpu}}" $config_file \
           && bash ./CI_connection.sh ${{github.event.inputs.model_list}} ${{github.event.inputs.deeprec_params}} ${{github.event.inputs.tf_params}} \
           echo ##########################################config.properties############################################
           cat $config_file
           echo #######################################################################################################      
      - name: run the build process
        run: |
          cd /home/shanlin/DeepRec_CI/gstep_benchmark/
          bash gstep_benchmark-action.sh
      - name: output the result
        run: |          
          echo "the build process has been executed successfully"

