# This is a basic workflow to help you get started with Actions

name: gstep_benmark

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deeprec_test_image:
        description: 'DeepRec Benchmark Image'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:latest'
      tf_test_image:
        description: 'STOCK TF Benchmark Image'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf'
      model_list:
        description: 'Model list'
        default: 'WDL DSSM DeepFM DLRM DIEN DIN'
      deeprec_param1:
        description: 'DeepRec Benchmark Parameter1'
        default: '--timeline 1000'
      deeprec_param2:
        description: 'DeepRec Benchmark Parameter2'
        default: '--fusion'
      tf_param1:
        description: 'TF Benchmark Parameter1'
        default: '--timeline 1000'
      tf_param2:
        description: 'TF Benchmark Parameter2'
      cpu:
        description: 'CPU'
        default: '24-47'
      optimation:
        description: 'Turn optimation On'
        type: boolean
        default: 'true'
      weekly_tag:
        description: 'Regression Benmark'
        type: boolean
        default: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gstep_benchmark:
    # The type of runner that the job will run on
    runs-on: gstep_benchmark

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: modify the config file by inputs params
        run: |
           config_file="/home/shanlin/DeepRec_CI/gstep_benchmark/config.properties"
           cd /home/shanlin/
           if [[ ! -d DeepRec_CI ]];then
               git clone https://github.com/GosTraight2020/DeepRec_CI.git
               if [[ $? != 1 ]];then
                    exit 1;
               fi
           fi
           cd ./DeepRec_CI/ \
           && git pull \
           && cd ./gstep_benchmark/ \
           && sed -i "2c, deeprec_test_image ${{github.event.inputs.deeprec_test_image}}" $config_file\
           && sed -i "3c, tf_test_image ${{github.event.inputs.tf_test_image}}" $config_file\
           && sed -i "17c, cpus ${{github.event.inputs.cpu}}" $config_file \
           && bash ./CI_connection.sh "${{github.event.inputs.model_list}}" "${{github.event.inputs.deeprec_param1}}" "${{github.event.inputs.deeprec_param1}}" "${{github.event.inputs.tf_param1}}" "${{github.event.inputs.tf_param2}}"
           echo ##########################################config.properties############################################
           cat $config_file
           echo #######################################################################################################      
      - name: output the result
        run: |          
          echo "the build process has been executed successfully"

