# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch_name'
        default: 'main'
      commit_id:
        description: 'commit id'
      base_image:
        description: 'the image you want to build based on'
        default: 'cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf'
      code_repo:
        description: 'the repo you wanna to build'
        default: 'https://github.com/alibaba/DeepRec.git'
      latest:
        description: 'weather tag as the latest'
        type: boolean
        default: 'no'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: acc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: modify the config file by inputs params
        run: |
          echo ${{github.event.inputs.latest}}
          cd /home/shanlin/
          if [[ ! -d DeepRec_CI ]];then
              sudo git clone https://github.com/GosTraight2020/DeepRec_CI.git
          fi
          sed -i '3c commit_id ${{github.event.inputs.commit_id}}' /home/shanlin/DeepRec_CI/acc_auc_benchmark/config.properties
          sed -i '4c branch_name ${{github.event.inputs.branch_name}}' /home/shanlin/DeepRec_CI/acc_auc_benchmark/config.properties
          sed -i '9c base_image_modelzoo ${{github.event.inputs.base_image}}' /home/shanlin/DeepRec_CI/acc_auc_benchmark/config.properties
          sed -i '19c code_repo ${{github.event.inputs.code_repo}}' /home/shanlin/DeepRec_CI/acc_auc_benchmark/config.properties
          cat /home/shanlin/DeepRec_CI/acc_auc_benchmark/config.properties
          cd DeepRec_CI/acc_auc_benchmark/build
          if [[ ${{github.event.inputs.latest}} == yes ]];then
              bash image_build-action.sh -l
          else 
              bash iamge_build-action.sh
          fi
